/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class Activity {
    'id': number;
    'type': ActivityTypeEnum;
    'entityId': number;
    'actor': User;
    'actorId': number;
    'action': string;
    'target': ActivityTargetEnum;
    'time': Date;
    'changes': Array<string> | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ActivityTypeEnum",
            "format": ""
        },
        {
            "name": "entityId",
            "baseName": "entityId",
            "type": "number",
            "format": ""
        },
        {
            "name": "actor",
            "baseName": "actor",
            "type": "User",
            "format": ""
        },
        {
            "name": "actorId",
            "baseName": "actorId",
            "type": "number",
            "format": ""
        },
        {
            "name": "action",
            "baseName": "action",
            "type": "string",
            "format": ""
        },
        {
            "name": "target",
            "baseName": "target",
            "type": "ActivityTargetEnum",
            "format": ""
        },
        {
            "name": "time",
            "baseName": "time",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "changes",
            "baseName": "changes",
            "type": "Array<string>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Activity.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ActivityTypeEnum {
    Application = 'application',
    User = 'user'
}
export enum ActivityTargetEnum {
    Application = 'application',
    Status = 'status',
    User = 'user',
    Profile = 'profile'
}

