/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ApplicationStatistics {
    'created': number;
    'submitted': number;
    'returned': number;
    'reviewed': number;
    'approved': number;
    'declined': number;
    'signed': number;
    'canceled': number;
    'total': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "created",
            "baseName": "created",
            "type": "number",
            "format": ""
        },
        {
            "name": "submitted",
            "baseName": "submitted",
            "type": "number",
            "format": ""
        },
        {
            "name": "returned",
            "baseName": "returned",
            "type": "number",
            "format": ""
        },
        {
            "name": "reviewed",
            "baseName": "reviewed",
            "type": "number",
            "format": ""
        },
        {
            "name": "approved",
            "baseName": "approved",
            "type": "number",
            "format": ""
        },
        {
            "name": "declined",
            "baseName": "declined",
            "type": "number",
            "format": ""
        },
        {
            "name": "signed",
            "baseName": "signed",
            "type": "number",
            "format": ""
        },
        {
            "name": "canceled",
            "baseName": "canceled",
            "type": "number",
            "format": ""
        },
        {
            "name": "total",
            "baseName": "total",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationStatistics.attributeTypeMap;
    }

    public constructor() {
    }
}

