/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Application } from '../models/Application';
import { PageMetaDto } from '../models/PageMetaDto';
import { HttpFile } from '../http/http';

export class ApplicationsControllerMy200Response {
    'meta': PageMetaDto;
    'data': Array<Application>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "meta",
            "baseName": "meta",
            "type": "PageMetaDto",
            "format": ""
        },
        {
            "name": "data",
            "baseName": "data",
            "type": "Array<Application>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ApplicationsControllerMy200Response.attributeTypeMap;
    }

    public constructor() {
    }
}

