/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Country } from '../models/Country';
import { FileType } from '../models/FileType';
import { Specimen } from '../models/Specimen';
import { User } from '../models/User';
import { HttpFile } from '../http/http';

export class Application {
    'createdAt': Date;
    'updatedAt': Date | null;
    'deletedAt': Date | null;
    'id': number;
    'user': User;
    'userId': number;
    /**
    * No.
    */
    'number': string | null;
    'issueDate': any;
    'type': ApplicationTypeEnum;
    /**
    * 3. Importer
    */
    'importer': string;
    /**
    * 5. Country of import
    */
    'importCountry': Country;
    /**
    * 5. Country of import
    */
    'importCountryId': number;
    /**
    * 1. Exporter/Re-exporter
    */
    'exporter': string;
    /**
    * 4. Country of (re)-export
    */
    'exportCountry': Country;
    /**
    * 4. Country of (re)-export
    */
    'exportCountryId': number;
    /**
    * 2. Last day of validity
    */
    'validity': Date | null;
    /**
    * 6. Authorized location for live specimen of List A species
    */
    'speciesLocation': string | null;
    /**
    * 7. Issuing Management Authority
    */
    'issuingManagementAuthority': string | null;
    'specimen': Specimen;
    /**
    * 21. Scientific name of species
    */
    'speciesScientificName': string;
    /**
    * 22. Common name of species
    */
    'commonName': string;
    'comment': string;
    'files': Array<string>;
    'fileIds': Array<string>;
    'scientificOpinionFile': FileType | null;
    'scientificOpinionFileId': string | null;
    'proofOfOriginFile': FileType | null;
    'proofOfOriginFileId': string | null;
    'exportPermitFile': FileType | null;
    'exportPermitFileId': string | null;
    'previousPermitsReportFile': FileType | null;
    'previousPermitsReportFileId': string | null;
    'paymentReceiptFile': FileType | null;
    'paymentReceiptFileId': string | null;
    'status': ApplicationStatusEnum;
    'statusReason': string | null;
    'reviewer': User | null;
    'reviewerId': number | null;
    'approvedBy': User | null;
    'approvedById': number | null;
    'signedBy': User | null;
    'signedById': number | null;
    'permit': FileType | null;
    'permitId': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedAt",
            "baseName": "deletedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "user",
            "baseName": "user",
            "type": "User",
            "format": ""
        },
        {
            "name": "userId",
            "baseName": "userId",
            "type": "number",
            "format": ""
        },
        {
            "name": "number",
            "baseName": "number",
            "type": "string",
            "format": ""
        },
        {
            "name": "issueDate",
            "baseName": "issueDate",
            "type": "any",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "ApplicationTypeEnum",
            "format": ""
        },
        {
            "name": "importer",
            "baseName": "importer",
            "type": "string",
            "format": ""
        },
        {
            "name": "importCountry",
            "baseName": "importCountry",
            "type": "Country",
            "format": ""
        },
        {
            "name": "importCountryId",
            "baseName": "importCountryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "exporter",
            "baseName": "exporter",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportCountry",
            "baseName": "exportCountry",
            "type": "Country",
            "format": ""
        },
        {
            "name": "exportCountryId",
            "baseName": "exportCountryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "validity",
            "baseName": "validity",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "speciesLocation",
            "baseName": "speciesLocation",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuingManagementAuthority",
            "baseName": "issuingManagementAuthority",
            "type": "string",
            "format": ""
        },
        {
            "name": "specimen",
            "baseName": "specimen",
            "type": "Specimen",
            "format": ""
        },
        {
            "name": "speciesScientificName",
            "baseName": "speciesScientificName",
            "type": "string",
            "format": ""
        },
        {
            "name": "commonName",
            "baseName": "commonName",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "files",
            "baseName": "files",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "fileIds",
            "baseName": "fileIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "scientificOpinionFile",
            "baseName": "scientificOpinionFile",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "scientificOpinionFileId",
            "baseName": "scientificOpinionFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "proofOfOriginFile",
            "baseName": "proofOfOriginFile",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "proofOfOriginFileId",
            "baseName": "proofOfOriginFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportPermitFile",
            "baseName": "exportPermitFile",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "exportPermitFileId",
            "baseName": "exportPermitFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousPermitsReportFile",
            "baseName": "previousPermitsReportFile",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "previousPermitsReportFileId",
            "baseName": "previousPermitsReportFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentReceiptFile",
            "baseName": "paymentReceiptFile",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "paymentReceiptFileId",
            "baseName": "paymentReceiptFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "ApplicationStatusEnum",
            "format": ""
        },
        {
            "name": "statusReason",
            "baseName": "statusReason",
            "type": "string",
            "format": ""
        },
        {
            "name": "reviewer",
            "baseName": "reviewer",
            "type": "User",
            "format": ""
        },
        {
            "name": "reviewerId",
            "baseName": "reviewerId",
            "type": "number",
            "format": ""
        },
        {
            "name": "approvedBy",
            "baseName": "approvedBy",
            "type": "User",
            "format": ""
        },
        {
            "name": "approvedById",
            "baseName": "approvedById",
            "type": "number",
            "format": ""
        },
        {
            "name": "signedBy",
            "baseName": "signedBy",
            "type": "User",
            "format": ""
        },
        {
            "name": "signedById",
            "baseName": "signedById",
            "type": "number",
            "format": ""
        },
        {
            "name": "permit",
            "baseName": "permit",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "permitId",
            "baseName": "permitId",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Application.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ApplicationTypeEnum {
    Import = 'import',
    Export = 'export',
    Reexport = 'reexport',
    Other = 'other'
}
export enum ApplicationStatusEnum {
    Created = 'created',
    Submitted = 'submitted',
    Returned = 'returned',
    Reviewed = 'reviewed',
    Approved = 'approved',
    Declined = 'declined',
    Signed = 'signed',
    Canceled = 'canceled'
}

