/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class AssignApplicationDto {
    'reviewerId': number;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "reviewerId",
            "baseName": "reviewerId",
            "type": "number",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return AssignApplicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}

