/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class ChangeStatusApplicationDto {
    'status': ChangeStatusApplicationDtoStatusEnum;
    'statusReason': string | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "status",
            "baseName": "status",
            "type": "ChangeStatusApplicationDtoStatusEnum",
            "format": ""
        },
        {
            "name": "statusReason",
            "baseName": "statusReason",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return ChangeStatusApplicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum ChangeStatusApplicationDtoStatusEnum {
    Created = 'created',
    Submitted = 'submitted',
    Returned = 'returned',
    Reviewed = 'reviewed',
    Approved = 'approved',
    Declined = 'declined',
    Signed = 'signed',
    Canceled = 'canceled'
}

