/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Address } from '../models/Address';
import { FileType } from '../models/FileType';
import { Individual } from '../models/Individual';
import { HttpFile } from '../http/http';

export class Company {
    'createdAt': Date;
    'updatedAt': Date | null;
    'deletedAt': Date | null;
    'id': number;
    'name': string;
    'address': Address;
    'taxNumber': number;
    'identificationDocument': FileType;
    'identificationDocumentId': string;
    'contact': Individual;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedAt",
            "baseName": "deletedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "name",
            "baseName": "name",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "Address",
            "format": ""
        },
        {
            "name": "taxNumber",
            "baseName": "taxNumber",
            "type": "number",
            "format": ""
        },
        {
            "name": "identificationDocument",
            "baseName": "identificationDocument",
            "type": "FileType",
            "format": ""
        },
        {
            "name": "identificationDocumentId",
            "baseName": "identificationDocumentId",
            "type": "string",
            "format": ""
        },
        {
            "name": "contact",
            "baseName": "contact",
            "type": "Individual",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Company.attributeTypeMap;
    }

    public constructor() {
    }
}

