/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpecimenApplicantDto } from '../models/SpecimenApplicantDto';
import { HttpFile } from '../http/http';

export class CreateApplicationDto {
    'type': CreateApplicationDtoTypeEnum;
    /**
    * 3. Importer
    */
    'importer': string;
    /**
    * 5. Country of import
    */
    'importCountryId': number;
    /**
    * 1. Exporter/Re-exporter
    */
    'exporter': string;
    /**
    * 4. Country of (re)-export
    */
    'exportCountryId': number;
    'specimen': SpecimenApplicantDto;
    /**
    * 21. Scientific name of species
    */
    'speciesScientificName': string;
    /**
    * 22. Common name of species
    */
    'commonName': string;
    'comment': string;
    'fileIds'?: Array<string>;
    'proofOfOriginFileId': string | null;
    'exportPermitFileId': string | null;
    'previousPermitsReportFileId': string | null;
    'paymentReceiptFileId': string;
    'status': CreateApplicationDtoStatusEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "type",
            "baseName": "type",
            "type": "CreateApplicationDtoTypeEnum",
            "format": ""
        },
        {
            "name": "importer",
            "baseName": "importer",
            "type": "string",
            "format": ""
        },
        {
            "name": "importCountryId",
            "baseName": "importCountryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "exporter",
            "baseName": "exporter",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportCountryId",
            "baseName": "exportCountryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "specimen",
            "baseName": "specimen",
            "type": "SpecimenApplicantDto",
            "format": ""
        },
        {
            "name": "speciesScientificName",
            "baseName": "speciesScientificName",
            "type": "string",
            "format": ""
        },
        {
            "name": "commonName",
            "baseName": "commonName",
            "type": "string",
            "format": ""
        },
        {
            "name": "comment",
            "baseName": "comment",
            "type": "string",
            "format": ""
        },
        {
            "name": "fileIds",
            "baseName": "fileIds",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "proofOfOriginFileId",
            "baseName": "proofOfOriginFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "exportPermitFileId",
            "baseName": "exportPermitFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "previousPermitsReportFileId",
            "baseName": "previousPermitsReportFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "paymentReceiptFileId",
            "baseName": "paymentReceiptFileId",
            "type": "string",
            "format": ""
        },
        {
            "name": "status",
            "baseName": "status",
            "type": "CreateApplicationDtoStatusEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateApplicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum CreateApplicationDtoTypeEnum {
    Import = 'import',
    Export = 'export',
    Reexport = 'reexport',
    Other = 'other'
}
export enum CreateApplicationDtoStatusEnum {
    Created = 'created',
    Submitted = 'submitted',
    Returned = 'returned',
    Reviewed = 'reviewed',
    Approved = 'approved',
    Declined = 'declined',
    Signed = 'signed',
    Canceled = 'canceled'
}

