/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { AddressDto } from '../models/AddressDto';
import { DocumentDto } from '../models/DocumentDto';
import { HttpFile } from '../http/http';

export class CreateIndividualProfileDto {
    'firstName': string;
    'lastName': string;
    'address': AddressDto;
    'document': DocumentDto;
    'phoneNumber': string;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "firstName",
            "baseName": "firstName",
            "type": "string",
            "format": ""
        },
        {
            "name": "lastName",
            "baseName": "lastName",
            "type": "string",
            "format": ""
        },
        {
            "name": "address",
            "baseName": "address",
            "type": "AddressDto",
            "format": ""
        },
        {
            "name": "document",
            "baseName": "document",
            "type": "DocumentDto",
            "format": ""
        },
        {
            "name": "phoneNumber",
            "baseName": "phoneNumber",
            "type": "string",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return CreateIndividualProfileDto.attributeTypeMap;
    }

    public constructor() {
    }
}

