/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Document {
    'id': string;
    'issuingCountryId': number;
    'type': DocumentTypeEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "issuingCountryId",
            "baseName": "issuingCountryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "type",
            "baseName": "type",
            "type": "DocumentTypeEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Document.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum DocumentTypeEnum {
    PersonalId = 'personalId',
    Passport = 'passport'
}

