/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { FilterApplicationDto } from '../models/FilterApplicationDto';
import { SortApplicationDto } from '../models/SortApplicationDto';
import { HttpFile } from '../http/http';

export class QueryApplicationDto {
    'page'?: number;
    'limit'?: number;
    'filters'?: FilterApplicationDto;
    'sort'?: Array<SortApplicationDto>;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "page",
            "baseName": "page",
            "type": "number",
            "format": ""
        },
        {
            "name": "limit",
            "baseName": "limit",
            "type": "number",
            "format": ""
        },
        {
            "name": "filters",
            "baseName": "filters",
            "type": "FilterApplicationDto",
            "format": ""
        },
        {
            "name": "sort",
            "baseName": "sort",
            "type": "Array<SortApplicationDto>",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return QueryApplicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}

