/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SortApplicationDto {
    'orderBy': SortApplicationDtoOrderByEnum;
    'order'?: SortApplicationDtoOrderEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "orderBy",
            "baseName": "orderBy",
            "type": "SortApplicationDtoOrderByEnum",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "SortApplicationDtoOrderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SortApplicationDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SortApplicationDtoOrderByEnum {
    UserId = 'userId',
    ReviewerId = 'reviewerId',
    Status = 'status',
    Type = 'type',
    CreatedAt = 'createdAt',
    UpdatedAt = 'updatedAt',
    DeletedAt = 'deletedAt'
}
export enum SortApplicationDtoOrderEnum {
    Asc = 'ASC',
    Desc = 'DESC'
}

