/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class SpecimenDescriptionDto {
    'description': string;
    'tradeTermCode': SpecimenDescriptionDtoTradeTermCodeEnum;
    'marks': Array<string>;
    'gender': SpecimenDescriptionDtoGenderEnum | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "string",
            "format": ""
        },
        {
            "name": "tradeTermCode",
            "baseName": "tradeTermCode",
            "type": "SpecimenDescriptionDtoTradeTermCodeEnum",
            "format": ""
        },
        {
            "name": "marks",
            "baseName": "marks",
            "type": "Array<string>",
            "format": ""
        },
        {
            "name": "gender",
            "baseName": "gender",
            "type": "SpecimenDescriptionDtoGenderEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpecimenDescriptionDto.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SpecimenDescriptionDtoTradeTermCodeEnum {
    Bal = 'BAL',
    Bar = 'BAR',
    Bod = 'BOD',
    Bon = 'BON',
    Cal = 'CAL',
    Cap = 'CAP',
    Car = 'CAR',
    Boc = 'BOC',
    Hoc = 'HOC',
    Ivc = 'IVC',
    Cav = 'CAV',
    Chp = 'CHP',
    Cla = 'CLA',
    Clo = 'CLO',
    Cor = 'COR',
    Cos = 'COS',
    Cul = 'CUL',
    Der = 'DER',
    Dpl = 'DPL',
    Ear = 'EAR',
    Egg = 'EGG',
    Egl = 'EGL',
    Esh = 'ESH',
    Ext = 'EXT',
    Fea = 'FEA',
    Fib = 'FIB',
    Dfn = 'DFN',
    Ffn = 'FFN',
    Fig = 'FIG',
    Flo = 'FLO',
    Fpt = 'FPT',
    Leg = 'LEG',
    Fru = 'FRU',
    Foo = 'FOO',
    Oil = 'OIL',
    Prl = 'PRL',
    Key = 'KEY',
    Bop = 'BOP',
    Hop = 'HOP',
    Ivp = 'IVP',
    Pla = 'PLA',
    Ply = 'PLY',
    Pow = 'POW',
    Pup = 'PUP',
    Roo = 'ROO',
    Rug = 'RUG',
    Ros = 'ROS',
    Saw = 'SAW',
    Sca = 'SCA',
    See = 'SEE',
    She = 'SHE',
    Sid = 'SID',
    Ske = 'SKE',
    Ski = 'SKI',
    Skp = 'SKP',
    Sku = 'SKU',
    Sou = 'SOU',
    Spe = 'SPE',
    Ste = 'STE',
    Swi = 'SWI',
    Tai = 'TAI',
    Thd = 'THD',
    Tim = 'TIM',
    Tee = 'TEE',
    Trw = 'TRW',
    Tro = 'TRO',
    Tru = 'TRU',
    Tus = 'TUS',
    Ven = 'VEN',
    Wax = 'WAX',
    Wpr = 'WPR'
}
export enum SpecimenDescriptionDtoGenderEnum {
    Male = 'male',
    Female = 'female',
    Other = 'other'
}

