/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

/**
* 9. Net mass (kg)
*/
export class SpecimenNetMass {
    'value': number;
    'unit': SpecimenNetMassUnitEnum;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "value",
            "baseName": "value",
            "type": "number",
            "format": ""
        },
        {
            "name": "unit",
            "baseName": "unit",
            "type": "SpecimenNetMassUnitEnum",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return SpecimenNetMass.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SpecimenNetMassUnitEnum {
    G = 'g',
    Kg = 'kg',
    L = 'l',
    Ml = 'ml',
    M = 'm',
    M2 = 'm2',
    Cm = 'cm',
    M3 = 'm3'
}

