/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpecimenCountryData } from '../models/SpecimenCountryData';
import { SpecimenDescription } from '../models/SpecimenDescription';
import { SpecimenNetMass } from '../models/SpecimenNetMass';
import { HttpFile } from '../http/http';

export class Specimen {
    /**
    * 8. Description Of specimens (incl. marks, sex, date of birth for live animals)
    */
    'description': SpecimenDescription;
    'netMass': SpecimenNetMass | null;
    /**
    * 10. Quantity
    */
    'quantity': number | null;
    /**
    * 11. CITES Appendix
    */
    'citesAppendix': SpecimenCitesAppendixEnum;
    /**
    * 12. List of species
    */
    'speciesList': SpecimenSpeciesListEnum;
    /**
    * 13. Source
    */
    'source': SpecimenSourceEnum;
    /**
    * 14. Purpose
    */
    'purpose': SpecimenPurposeEnum;
    'specimenOrigin': SpecimenCountryData;
    'specimenExport': SpecimenCountryData;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "description",
            "baseName": "description",
            "type": "SpecimenDescription",
            "format": ""
        },
        {
            "name": "netMass",
            "baseName": "netMass",
            "type": "SpecimenNetMass",
            "format": ""
        },
        {
            "name": "quantity",
            "baseName": "quantity",
            "type": "number",
            "format": ""
        },
        {
            "name": "citesAppendix",
            "baseName": "citesAppendix",
            "type": "SpecimenCitesAppendixEnum",
            "format": ""
        },
        {
            "name": "speciesList",
            "baseName": "speciesList",
            "type": "SpecimenSpeciesListEnum",
            "format": ""
        },
        {
            "name": "source",
            "baseName": "source",
            "type": "SpecimenSourceEnum",
            "format": ""
        },
        {
            "name": "purpose",
            "baseName": "purpose",
            "type": "SpecimenPurposeEnum",
            "format": ""
        },
        {
            "name": "specimenOrigin",
            "baseName": "specimenOrigin",
            "type": "SpecimenCountryData",
            "format": ""
        },
        {
            "name": "specimenExport",
            "baseName": "specimenExport",
            "type": "SpecimenCountryData",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Specimen.attributeTypeMap;
    }

    public constructor() {
    }
}


export enum SpecimenCitesAppendixEnum {
    I = 'I',
    Ii = 'II',
    Iii = 'III',
    NotListed = 'notListed'
}
export enum SpecimenSpeciesListEnum {
    A = 'A',
    B = 'B',
    C = 'C',
    D = 'D',
    NotListed = 'notListed'
}
export enum SpecimenSourceEnum {
    W = 'W',
    R = 'R',
    D = 'D',
    A = 'A',
    C = 'C',
    F = 'F',
    I = 'I',
    O = 'O',
    U = 'U',
    X = 'X',
    Y = 'Y'
}
export enum SpecimenPurposeEnum {
    B = 'B',
    E = 'E',
    G = 'G',
    H = 'H',
    L = 'L',
    M = 'M',
    N = 'N',
    P = 'P',
    Q = 'Q',
    S = 'S',
    T = 'T',
    Z = 'Z'
}

