/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { HttpFile } from '../http/http';

export class Species {
    'createdAt': Date;
    'updatedAt': Date | null;
    'deletedAt': Date | null;
    'id': number;
    'kingdom': any;
    'phylum': any;
    '_class': any;
    'order': any;
    'family': any;
    'genus': any;
    'species': any;
    'subspecies': any;
    'scientificName': any;
    'author': any;
    'rank': any;
    'listing': any;
    'party': any;
    'listedUnder': any;
    'fullNote': any;
    'fullNote2': any;
    'allDistributionFullNames': any;
    'allDistributionISOCodes': any;
    'nativeDistributionFullNames': any;
    'introducedDistribution': any;
    'introducedDistribution2': any;
    'reintroducedDistribution': any;
    'extinctDistribution': any;
    'extinctDistribution2': any;
    'distributionUncertain': any;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "createdAt",
            "baseName": "createdAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "updatedAt",
            "baseName": "updatedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "deletedAt",
            "baseName": "deletedAt",
            "type": "Date",
            "format": "date-time"
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "number",
            "format": ""
        },
        {
            "name": "kingdom",
            "baseName": "kingdom",
            "type": "any",
            "format": ""
        },
        {
            "name": "phylum",
            "baseName": "phylum",
            "type": "any",
            "format": ""
        },
        {
            "name": "_class",
            "baseName": "class",
            "type": "any",
            "format": ""
        },
        {
            "name": "order",
            "baseName": "order",
            "type": "any",
            "format": ""
        },
        {
            "name": "family",
            "baseName": "family",
            "type": "any",
            "format": ""
        },
        {
            "name": "genus",
            "baseName": "genus",
            "type": "any",
            "format": ""
        },
        {
            "name": "species",
            "baseName": "species",
            "type": "any",
            "format": ""
        },
        {
            "name": "subspecies",
            "baseName": "subspecies",
            "type": "any",
            "format": ""
        },
        {
            "name": "scientificName",
            "baseName": "scientificName",
            "type": "any",
            "format": ""
        },
        {
            "name": "author",
            "baseName": "author",
            "type": "any",
            "format": ""
        },
        {
            "name": "rank",
            "baseName": "rank",
            "type": "any",
            "format": ""
        },
        {
            "name": "listing",
            "baseName": "listing",
            "type": "any",
            "format": ""
        },
        {
            "name": "party",
            "baseName": "party",
            "type": "any",
            "format": ""
        },
        {
            "name": "listedUnder",
            "baseName": "listedUnder",
            "type": "any",
            "format": ""
        },
        {
            "name": "fullNote",
            "baseName": "fullNote",
            "type": "any",
            "format": ""
        },
        {
            "name": "fullNote2",
            "baseName": "fullNote2",
            "type": "any",
            "format": ""
        },
        {
            "name": "allDistributionFullNames",
            "baseName": "allDistributionFullNames",
            "type": "any",
            "format": ""
        },
        {
            "name": "allDistributionISOCodes",
            "baseName": "allDistributionISOCodes",
            "type": "any",
            "format": ""
        },
        {
            "name": "nativeDistributionFullNames",
            "baseName": "nativeDistributionFullNames",
            "type": "any",
            "format": ""
        },
        {
            "name": "introducedDistribution",
            "baseName": "introducedDistribution",
            "type": "any",
            "format": ""
        },
        {
            "name": "introducedDistribution2",
            "baseName": "introducedDistribution2",
            "type": "any",
            "format": ""
        },
        {
            "name": "reintroducedDistribution",
            "baseName": "reintroducedDistribution",
            "type": "any",
            "format": ""
        },
        {
            "name": "extinctDistribution",
            "baseName": "extinctDistribution",
            "type": "any",
            "format": ""
        },
        {
            "name": "extinctDistribution2",
            "baseName": "extinctDistribution2",
            "type": "any",
            "format": ""
        },
        {
            "name": "distributionUncertain",
            "baseName": "distributionUncertain",
            "type": "any",
            "format": ""
        }    ];

    static getAttributeTypeMap() {
        return Species.attributeTypeMap;
    }

    public constructor() {
    }
}

