/**
 * MOEPP CITES API
 * MOEPP CITES API docs
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { SpecimenCountryDataCountry } from '../models/SpecimenCountryDataCountry';
import { HttpFile } from '../http/http';

export class SpecimenCountryData {
    'country': SpecimenCountryDataCountry | null;
    /**
    * 15. Country of origin/18. Country of last re-export
    */
    'countryId': number | null;
    /**
    * 16. Permit No./19. Certificate No.
    */
    'id': string | null;
    /**
    * 17. Date of issue/20. Date of issue
    */
    'issueDate': Date | null;

    static readonly discriminator: string | undefined = undefined;

    static readonly attributeTypeMap: Array<{name: string, baseName: string, type: string, format: string}> = [
        {
            "name": "country",
            "baseName": "country",
            "type": "SpecimenCountryDataCountry",
            "format": ""
        },
        {
            "name": "countryId",
            "baseName": "countryId",
            "type": "number",
            "format": ""
        },
        {
            "name": "id",
            "baseName": "id",
            "type": "string",
            "format": ""
        },
        {
            "name": "issueDate",
            "baseName": "issueDate",
            "type": "Date",
            "format": "date-time"
        }    ];

    static getAttributeTypeMap() {
        return SpecimenCountryData.attributeTypeMap;
    }

    public constructor() {
    }
}

