name: NestJS API CI

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Run e2e tests for NestJS with TypeORM
        id: relational
        run: docker compose -f docker-compose.ci.yaml --env-file .env.example -p ci-relational up --build --exit-code-from api

      - name: Copy prod.log from container to host
        if: ${{ failure() && steps.conclusion == 'failure' }}
        run: docker cp ci-relational-api-1:/usr/src/app/prod.log .

      - name: Upload prod.log to artifacts for debugging
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: prod-logs
          path: prod.log
      
      # - name: deploy
      #   if: success() &&  github.event_name != 'pull_request'
      #   env:
      #       PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
      #       HOSTNAME: ${{secrets.REMOTE_HOST}}
      #       USER_NAME: ${{secrets.REMOTE_USER}}
      #   run: |
      #     echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
      #     ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '

      #         ~/deploy.sh
      #         '
